### ISSUE TITLE
Why prime sieve?

### ISSUE THREAD

**Issue by Rudxain** [thomwiggers/factorial#14]
I've been reading the code, and I still don't get why a sieve is needed at all. Why not just use the `array.rs` for everything? Is it because of generics?

**Comment by Rudxain** [comment]
I've started reading the conversation at #9, I still don't understand, but it seems it's because of generics (to support arbitrary-precision when possible). Is that correct?

**Comment by thomwiggers** [comment]
@marcantoinem will be able to confirm this, but the main problem is the question of "where do you stop" with `array.rs`. For any larger inputs than what's included in `array.rs`, you would fall back to the naive implementation and thus have a big performance regression.

**Comment by Rudxain** [comment]
> "where do you stop"

If arbitrary precision isn't a concern, we could use `u128`s as a limit. In that case, `34!` is the biggest 128bit factorial, every other factorial wraps around, until we get all zeros (because big factorials have many trailing zeros). For `f64`s, the biggest finite factorial is `170!`.

This means that the table doesn't need to be big, because the `fn` can do a simple comparison to return a constant when an overflow happens (2^128-1 for `saturating` arithmetic, 0 for `wrapping`, and `Infinity` for floats)

**Comment by marcantoinem** [comment]
It stops using `array.rs` when we reach the limit of an `u128` which is the biggest primitive supported by the standard library. After that, it is designed to works with big number library like [BigInt](https://github.com/rust-num/num-bigint). And yes, this library use generics to implement factorial on these number, so we need primitives to support multiple big integer implementation.

Also, there's a gap where the naive algorithm is used because making a sieve is more expensive than calculating the factorial naively, but after that (around 1000!) it just switch to the prime sieve algorithm which has a better big o notation.

**Comment by Rudxain** [comment]
> it is designed to works with big number library like [BigInt](https://github.com/rust-num/num-bigint). And yes, this library use generics to implement factorial on these number, so we need primitives to support multiple big integer implementation.

Oooh, now I get it! This is genius. I need to do something similar in my [Ackermann crate](/Rudxain/ackermann.rs), it only supports arbitrary-precision via `num-bigint`. Thank you so much for the info!

> there's a gap where the naive algorithm is used

That reminds me of galactic algorithms (despite this not being one)
